[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"gdown==4.7.1",
	"playwright==1.35.0",
]

[project.optional-dependencies]
dev = [
	"black==23.3.0",
	"mypy==1.4.0",
	"ruff==0.0.275",
	"ssort==0.11.6",
]
