on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'test/Makefile'
      - 'test/package.json'
      - 'test/test.js'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'test/Makefile'
      - 'test/package.json'
      - 'test/test.js'

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Test
        run: |
          cd test/
          make
